version: "3"
services:
  food-hunting-bot:
    build: .
    restart: always
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm # This will share host memory with the container, which is required for Chrome to work properly